[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "has-blue-color"
version = "1.0.0"
description = "Detecta si una imagen contiene color azul usando OpenCV"
readme = "README.md"
license = { text = "MIT" }
authors = [
    { name="Juan Rey", email="sudo.delete.evil@gmail.com" }
]
requires-python = ">=3.10"

dependencies = [
    "numpy==2.2.3",
    "opencv-python==4.11.0.86"
]