apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  name: blacker
  user: blackeruser
  master: postgres-service
  slave: postgres-service
  port: "5432"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: streaming-config
data:
  redis: redis://redis-streaming-srv:6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slave-config
data:
  DATABASE_HOST: "mysql"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "service_slave"
  DATABASE_USER: "blacker"

