info:
  name: /ws
  type: websocket
  seq: 1

websocket:
  url: ws://localhost:3000/api/market/ws
  message:
    type: json
    data: |-
      {
        "action": "subscribe",
        "engine_id": "dydx-BTC-USD"
      }
  auth: inherit

settings:
  timeout: 0
  keepAliveInterval: 0
