export type InstrumentStatus = "active" | "inactive" | "delisted" | "halted";

export enum InstrumentType {
  SPOT = "spot",
  FUTURES = "futures",
  OPTIONS = "options",
  OTHER = "other",
}

export enum InstrumentMarginType {
  CROSS = "cross",
  ISOLATED = "isolated",
}

export enum InstrumentMarket {
  /** Cryptocurrencies (spot, futures, options) */
  CRYPTO = "crypto",

  /** Equities / stocks */
  STOCKS = "stocks",

  /** Foreign exchange */
  FOREX = "forex",

  /** Futures contracts (CME, ICE, crypto futures) */
  FUTURES = "futures",

  /** Options (equity, index, crypto options) */
  OPTIONS = "options",

  /** Indices (S&P 500, NASDAQ 100, DAX, etc) */
  INDICES = "indices",

  /** Commodities (gold, oil, wheat, etc) */
  COMMODITIES = "commodities",

  /** Bonds / fixed income */
  BONDS = "bonds",

  /** ETFs */
  ETFS = "etfs",

  /** CFDs (contracts for difference) */
  CFDS = "cfds",

  /** Mutual funds */
  FUNDS = "funds",

  /** Interest rate products */
  RATES = "rates",

  /** Synthetic / internal instruments */
  SYNTHETIC = "synthetic",

  /** Any other or unknown market */
  OTHER = "other",
}

export type Instrument = {
  /**
   * Database primary key.
   * UUID v7 generated by Postgres.
   * Immutable.
   */
  id: string;

  /**
   * Internal business identifier.
   * Stable across systems (DB, search, cache, logs).
   * Example: "binance-btc-usdt"
   */
  internalId: string;

  /**
   * Idempotent identifier used by search engines (Typesense, Meilisearch).
   * Must be deterministic and unique.
   */
  idempotentId: string;

  /**
   * Trading symbol as defined by the venue or market.
   * Examples: "BTCUSDT", "AAPL", "EURUSD"
   */
  symbol: string;

  /**
   * Human-friendly symbol for UI display.
   * Example: "BTC/USDT"
   */
  symbolDisplay: string;

  /**
   * Descriptive instrument name.
   * Example: "Bitcoin / Tether USD"
   */
  description: string;

  /**
   * Base asset of the instrument.
   * What is being bought or sold.
   * Example: "BTC"
   */
  base: string;

  /**
   * Quote asset of the instrument.
   * What the price is denominated in.
   * Example: "USDT"
   */
  quote: string;

  /**
   * Exchange, broker, or venue name.
   * Example: "Binance", "NASDAQ", "CME"
   */
  exchange: string;

  /**
   * Country or jurisdiction where the exchange operates.
   * Example: "US", "JP", "SG"
   */
  exchangeCountry: string;

  /**
   * Market category.
   * Examples: "crypto", "stocks", "forex", "futures"
   */
  market: InstrumentMarket;

  /**
   * Instrument type.
   * Examples: "spot", "futures", "options", "other"
   */
  type: InstrumentType;

  /**
   * Name of the data or execution provider.
   * Example: "Binance", "Bloomberg", "InteractiveBrokers"
   */
  providerName: string;

  /**
   * Provider-specific instrument identifier.
   * Unique within the provider.
   */
  providerId: string;

  /**
   * Provider-specific trading symbol.
   */
  providerSymbol: string;

  /**
   * Instrument lifecycle status.
   * Examples: "active", "inactive", "delisted"
   */
  status: InstrumentStatus;

  /**
   * Whether the instrument is hidden from search and UI.
   */
  isHidden: boolean;

  /**
   * Indicates synthetic or derived instruments
   * (indexes, baskets, internal products).
   */
  isSynthetic: boolean;

  /**
   * International Securities Identification Number (if applicable).
   */
  isin?: string;

  /**
   * Committee on Uniform Securities Identification Procedures code.
   */
  cusip?: string;

  /**
   * Minimum allowed price increment.
   * Prices must be multiples of this value.
   */
  tickSize: number;

  /**
   * Quantity step size.
   * Defines the minimum increment for quantity.
   * Mutually exclusive with lotSize.
   */
  stepSize?: number;

  /**
   * Maximum number of decimal places allowed in price.
   * Must be consistent with tickSize.
   *
   * pricePrecision === decimals(tickSize)
   */
  pricePrecision: number;

  /**
   * Maximum number of decimal places allowed in quantity.
   * Only valid when stepSize is used.
   */
  quantityPrecision?: number;

  /**
   * Minimum quantity allowed per order.
   */
  minQuantity: number;

  /**
   * Maximum quantity allowed per order.
   */
  maxQuantity: number;

  /**
   * Minimum notional value required to place an order.
   * notional = price × quantity
   */
  minOrderValue: number;

  /**
   * Maximum notional value allowed per order.
   */
  maxOrderValue: number;

  /**
   * Fixed lot size for instruments traded in whole lots.
   * Mutually exclusive with stepSize and quantityPrecision.
   */
  lotSize?: number;

  /**
   * Contract size for derivatives.
   * Represents how much underlying one contract controls.
   */
  contractSize?: number;

  /**
   * Number of decimals used for UI display only.
   * Does NOT affect order validation.
   */
  displayDecimals: number;

  /**
   * Default leverage shown in UI.
   * Only valid if leverageMax exists.
   */
  leverage?: number;

  /**
   * Maximum leverage allowed by the venue.
   * If undefined, leverage is not supported.
   */
  leverageMax?: number;

  /**
   * Supported margin types for this instrument.
   * Examples: ["cross", "isolated"]
   */
  supportedMarginTypes: InstrumentMarginType[];

  /**
   * Initial margin requirement (as a fraction).
   */
  initialMargin?: number;

  /**
   * Maintenance margin requirement (as a fraction).
   */
  maintenanceMargin?: number;

  /**
   * Expiration date for expiring derivatives.
   * ISO-8601 format.
   */
  expiryDate?: string;

  /**
   * Settlement method for derivatives.
   * Examples: "cash", "physical"
   */
  settlementType?: string;

  /**
   * Settlement delay after trade execution.
   * Examples: "T+0", "T+1", "T+2"
   */
  settlementDelay?: "T+0" | "T+1" | "T+2";

  /**
   * Price multiplier applied for display or settlement.
   */
  priceMultiplier?: number;

  /**
   * Currency used for pricing the instrument.
   */
  pricingCurrency?: string;

  /**
   * Underlying asset for derivatives.
   */
  underlyingAsset?: string;

  /**
   * Currency used for settlement.
   */
  settlementCurrency?: string;

  /**
   * Trading hours for non-24/7 markets.
   */
  tradingHours?: {
    open: string; // HH:mm
    close: string; // HH:mm
    days: number[]; // 0 (Sunday) - 6 (Saturday)
  };

  /**
   * Tags for categorization and filtering.
   */
  tags: string[];

  /**
   * Priority for UI ranking and sorting.
   */
  priority?: number;

  /**
   * Icon URL used in UI.
   */
  iconUrl: string;

  /**
   * Highlight color for UI theming.
   */
  highlightColor: string;

  /**
   * Alternative symbols or aliases.
   */
  symbol_aliases: string[];

  /**
   * Precomputed full-text search string.
   * symbol + symbolDisplay + description + aliases
   */
  fullTextSearch?: string;

  /**
   *  User Fee tier plan.
   */
  feeTier?: string;

  /**
   * Maker fee percentage.
   */
  makerFee?: number;

  /**
   * Taker fee percentage.
   */
  takerFee?: number;

  /**
   * Typical bid-ask spread for informational purposes.
   * MUST NOT be used for execution.
   * MAKER TAKER SPREAD 
   */
  typicalSpread?: number;

  /**
   * Indicates whether the instrument is tradable.
   */
  isTradable?: boolean;

  /**
   * Indicates whether margin trading is allowed.
   */
  isMarginAllowed?: boolean;

  /**
   * Indicates whether KYC is required to trade.
   */
  requiresKYC?: boolean;

  /**
   * Indicates support for stop-limit orders.
   */
  supportsStopLimit?: boolean;

  /**
   * Indicates support for margin trading.
   */
  supportsMarginTrading?: boolean;

  /**
   * Indicates support for futures trading.
   */
  supportsFutures?: boolean;

  /**
   * Regulatory framework applicable to the instrument.
   */
  regulation?: string;

  /**
   * Timezone used for trading hours and sessions.
   */
  timezone: string;

  /**
   * Creation UNIX ms timestamp.
   */
  createdAt: number;

  /**
   * Last update UNIX ms timestamp.
   */
  updatedAt: number;

  /**
   * Lowercase symbol optimized for autocomplete.
   */
  symbol_lc?: string;

  /**
   * Additional search terms for discovery.
   */
  search_terms?: string[];

  /**Supported timeframes (5m, 1h, 4h, 1d, etc)*/
  supportedTimeframes: string[];

  /** Supports OHLCV */
  supportsOHLCV: true;
};

const instrumentFields = [
  // Required primary key for typesense
  { name: "id", type: "string" },

  // Business identifiers
  { name: "internalId", type: "string", index: false },

  // Searchable fields
  { name: "symbol", type: "string" },
  { name: "description", type: "string", optional: true },

  // Filterable / faceted fields
  { name: "base", type: "string", facet: true },
  { name: "quote", type: "string", facet: true },
  { name: "exchange", type: "string", facet: true },
  { name: "market", type: "string", facet: true },
  { name: "type", type: "string", facet: true }, // spot | futures | other

  // Optional identifiers
  { name: "isin", type: "string", optional: true, index: false },
  { name: "cusip", type: "string", optional: true, index: false },
];

export const INSTRUMENTS_COLLECTION = "instruments";

export const instrumentsSchema = {
  name: INSTRUMENTS_COLLECTION,
  fields: instrumentFields,
};
