apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-product
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-product
  template:
    metadata:
      labels:
        role: service-product
    spec:
      containers:
        - name: service-product
          image: pairfy/service-product
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                                       
            - name: SELLER_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: seller-token-secret
                  key: SELLER_TOKEN_KEY                       
            - name: POD_TIMEOUT
              value: '120000'   
            - name: EXPRESS_PORT
              value: "8000"
            - name: EXPRESS_TIMEOUT
              value: "120000"
            - name: DATABASE_HOST  
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: master  
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: database-config
                  key: port                                     
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password   
            - name: DATABASE_NAME
              value: service_product        
            - name: DATABASE_USER
              value: marketplace                                                                                                                                                                                       
            - name: CORS_DOMAINS
              value: "http://localhost:5173,http://localhost:8080,http://localhost:8081,http://localhost:443,localhost,https://pairfy.dev,https://dashboard.pairfy.dev"                          
          resources:
            limits:
              memory: "500Mi"
            requests:
              memory: "256Mi"       
---
apiVersion: v1
kind: Service
metadata:
  name: service-product
spec:
  selector:
    role: service-product
  ports:
    - name: service-product
      protocol: TCP
      port: 4000
      targetPort: 4000
