CREATE TABLE IF NOT EXISTS orders (
  id VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL,
  market VARCHAR(50) NOT NULL,
  slave VARCHAR(100) NOT NULL,
  symbol VARCHAR(50) NOT NULL,
  side VARCHAR(20) NOT NULL,

  price DECIMAL(20,10) NOT NULL,
  size DECIMAL(20,10) UNSIGNED NOT NULL,
  stop_loss DECIMAL(20,10) UNSIGNED NOT NULL,
  take_profit DECIMAL(20,10) UNSIGNED NOT NULL,

  account_risk DECIMAL(5,4) UNSIGNED NOT NULL,
  risk_usd DECIMAL(20,10) UNSIGNED NOT NULL,

  notified BOOLEAN NOT NULL,

  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,

  PRIMARY KEY (id),
  INDEX (slave),
  INDEX (symbol),
  INDEX (side)
) ENGINE=InnoDB;
