apiVersion: skaffold/v2alpha3
kind: Config

build:
  local:
    useDockerCLI: true
    push: false
    concurrency: 0
  tagPolicy:
    sha256: {}
  artifacts:       
    - image: pairfy/service-master
      context: service-master
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .  

    - image: pairfy/service-query
      context: service-query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: . 

    - image: pairfy/service-slave
      context: service-slave
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .

    - image: pairfy/service-hunter
      context: service-hunter
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.{ts,js,json,vue}'
            dest: .

deploy:
  statusCheckDeadlineSeconds: 600
  kubectl:
    manifests:
      - ./A/k8s/*
      - ./A/k8s-dev/*

