//@version=6
indicator(title="Money Flow Index + SMA", shorttitle="MFI+SMA", format=format.price, precision=2, timeframe="", timeframe_gaps=true)

// Inputs
length = input.int(title="Length MFI", defval=14, minval=1, maxval=2000)
smaLen = input.int(title="SMA Length", defval=14, minval=1, maxval=2000)

// MFI
src = hlc3
mf = ta.mfi(src, length)
plot(mf, "MFI", color=#7E57C2)

// SMA of MFI
mfi_sma = ta.sma(mf, smaLen)
plot(mfi_sma, "SMA MFI", color=color.yellow, linewidth=1)

// Levels
overbought = hline(80, title="Overbought", color=#787B86)
hline(50, "Middle Band", color=color.new(#787B86, 50))
oversold   = hline(20, title="Oversold", color=#787B86)

// Background fill
fill(overbought, oversold, color=color.rgb(126, 87, 194, 90), title="Background")

bgcolor(mf < mfi_sma ? color.new(color.red, 80) : na)