CREATE TABLE IF NOT EXISTS orders(
  id VARCHAR(100) NOT NULL,
  type VARCHAR(50) NOT NULL,
  status VARCHAR(100) DEFAULT "created",
  finished boolean DEFAULT FALSE,
  completed boolean DEFAULT FALSE,
  country VARCHAR(20) NOT NULL,
  buyer_pubkeyhash VARCHAR(100) NOT NULL,
  buyer_address VARCHAR(200) NOT NULL,
  buyer_wallet VARCHAR(50) NOT NULL,
  buyer_username VARCHAR(100) NOT NULL, 
  buyer_rsa_version INT UNSIGNED NOT NULL,
  buyer_rsa_public_key TEXT NOT NULL,
  seller_id VARCHAR(100) NOT NULL, 
  seller_pubkeyhash VARCHAR(100) NOT NULL,  
  seller_address VARCHAR(200) NOT NULL,
  seller_wallet VARCHAR(50) NOT NULL,
  seller_username VARCHAR(100) NOT NULL,
  seller_rsa_version INT UNSIGNED NOT NULL,
  product_id VARCHAR(100) NOT NULL,
  product_snapshot TEXT NOT NULL,
  contract_address VARCHAR(200) NOT NULL,
  contract_params TEXT NOT NULL,
  contract_state INT DEFAULT NULL,
  contract_price INT UNSIGNED NOT NULL,
  contract_quote INT UNSIGNED NOT NULL,
  contract_fee INT UNSIGNED NOT NULL,
  contract_units INT UNSIGNED NOT NULL,
  asset_name VARCHAR(50) NOT NULL,
  asset_price DECIMAL(10, 2) NOT NULL,
  watch_until BIGINT UNSIGNED NOT NULL,
  pending_until BIGINT UNSIGNED NOT NULL,
  shipping_until BIGINT UNSIGNED NOT NULL,
  expire_until BIGINT UNSIGNED NOT NULL,
  pending_tx VARCHAR(200) DEFAULT NULL,
  pending_block VARCHAR(200) DEFAULT NULL,
  pending_metadata TEXT DEFAULT NULL,
  pending_notified BOOLEAN DEFAULT FALSE,
  returned_tx VARCHAR(200) DEFAULT NULL,
  returned_block VARCHAR(200) DEFAULT NULL,
  returned_metadata TEXT DEFAULT NULL,
  returned_notified BOOLEAN DEFAULT FALSE,
  locking_tx VARCHAR(200) DEFAULT NULL,
  locking_block VARCHAR(200) DEFAULT NULL,
  locking_metadata TEXT DEFAULT NULL,
  locking_notified BOOLEAN DEFAULT FALSE,
  canceled_tx VARCHAR(200) DEFAULT NULL,
  canceled_block VARCHAR(200) DEFAULT NULL,
  canceled_metadata TEXT DEFAULT NULL,
  canceled_notified BOOLEAN DEFAULT FALSE,
  shipping_tx VARCHAR(200) DEFAULT NULL,
  shipping_block VARCHAR(200) DEFAULT NULL,
  shipping_metadata TEXT DEFAULT NULL,
  shipping_notified BOOLEAN DEFAULT FALSE,
  appealed_tx VARCHAR(200) DEFAULT NULL,
  appealed_block VARCHAR(200) DEFAULT NULL,  
  appealed_metadata TEXT DEFAULT NULL,
  appealed_notified BOOLEAN DEFAULT FALSE,
  received_tx VARCHAR(200) DEFAULT NULL,
  received_block VARCHAR(200) DEFAULT NULL,
  received_metadata TEXT DEFAULT NULL,
  received_notified BOOLEAN DEFAULT FALSE,
  collected_tx VARCHAR(200) DEFAULT NULL,
  collected_block VARCHAR(200) DEFAULT NULL,  
  collected_metadata TEXT DEFAULT NULL,
  collected_notified BOOLEAN DEFAULT FALSE,
  scanned_at BIGINT UNSIGNED DEFAULT 0,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  schema_v INT UNSIGNED NOT NULL,
  primary key(id),
  index idx_finished (finished),
  index idx_completed (completed),
  index idx_created_at (created_at),
  index idx_scanned_at (scanned_at),
  index idx_seller (seller_id),
  index idx_buyer (buyer_pubkeyhash),
  FOREIGN KEY (seller_id) REFERENCES sellers(id)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;