create table if not exists products(
  id varchar(100) not null,
  group_id varchar(100) not null,
  media_group_id varchar(100) not null,
  media_position JSON NOT NULL,
  status varchar(100) default 'created',
  moderated boolean default false,
  seller_id varchar(100) not null,
  thumbnail_url TEXT,
  name varchar(200) not null,
  price int unsigned not null,
  sku varchar(100) not null,
  model varchar(200) not null,
  brand varchar(200) not null,
  description JSON NOT NULL,   
  category varchar(100) not null,
  bullet_list JSON NOT NULL,                   
  color varchar(100) not null,
  condition_ varchar(50) not null,
  country varchar(10) not null,
  origin varchar(10) not null,
  city varchar(255) not null,
  postal varchar(50) not null,
  discount boolean not null,
  discount_value int unsigned not null,
  discount_percent int unsigned not null,
  created_at BIGINT UNSIGNED NOT NULL,
  updated_at BIGINT UNSIGNED NOT NULL,
  schema_v INT UNSIGNED NOT NULL,
  primary key(id),
  UNIQUE KEY unique_seller_sku (seller_id, sku),
  index idx_created_at (created_at),
  index idx_seller_id (seller_id),
  INDEX idx_group_id (group_id)
) ENGINE=InnoDB;


