apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-hunter
  labels:
    role: service-hunter
spec:
  replicas: 1
  selector:
    matchLabels:
      role: service-hunter
  template:
    metadata:
      labels:
        role: service-hunter
    spec:
      containers:
        - name: service-hunter
          image: pairfy/service-hunter
          env:
            - name: NODE_ENV
              value: "development"
            - name: SHOW_PLOTS
              value: "false"
            - name: START_AT
              value: "93"
            - name: COINGECKO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: coingecko-key-secret
                  key: key              
            - name: BINANCE_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-key-secret
                  key: key
            - name: BINANCE_SECRET
              valueFrom:
                secretKeyRef:
                  name: binance-secret-secret
                  key: secret
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: hunter-storage
              mountPath: /app/output
      volumes:
        - name: hunter-storage
          persistentVolumeClaim:
            claimName: pvc-hunter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hunter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-hunter
spec:
  selector:
    role: service-hunter
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
