apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave-8
  labels:
    role: slave-8
spec:
  replicas: 0
  selector:
    matchLabels:
      role: slave-8
  template:
    metadata:
      labels:
        role: slave-8
    spec:
      containers:
        - name: service-slave
          image: pairfy/service-slave
          env:
            - name: NODE_ENV
              value: "development"
            - name: SLAVE_NAME
              value: "slave-8"
            - name: SYMBOL
              value: "MORPHOUSDT"
            - name: LEVERAGE
              value: "5"
            - name: STOP_LOSS
              value: "0.97"
            - name: MARGIN_TYPE
              value: "ISOLATED"
            - name: ORDER_AMOUNT
              value: "500"
            - name: SHOW_PLOTS
              value: "false"
            - name: DATABASE_HOST
              value: "mysql"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "service_slave"
            - name: DATABASE_USER
              value: "blacker"
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password-secret
                  key: password
            - name: BINANCE_KEY
              valueFrom:
                secretKeyRef:
                  name: binance-key-secret
                  key: key
            - name: BINANCE_SECRET
              valueFrom:
                secretKeyRef:
                  name: binance-secret-secret
                  key: secret
                  
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: slave-storage
              mountPath: /app/output
      volumes:
        - name: slave-storage
          persistentVolumeClaim:
            claimName: pvc-slave-8
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-slave-8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: service-slave-8
spec:
  selector:
    role: slave-8
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
