info:
  name: add-series
  type: http
  seq: 7

http:
  method: POST
  url: http://localhost:3002/api/backtest/master/add-series
  body:
    type: json
    data: |-
      {
        "timeframe_id": "1m",
        "id": "ema",
        "kind": "EMA",
        "level": 1,
        "params": {
          "label": "EMA 55",
          "layer": "foreground",
          "color": "#FF9800",
          "priceTagColor": "#FF9800",
          "length": 55,
          "borderWidth": 2
        },
        "parent_id": "candlestick-1m-2705770294"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
