info:
  name: add-timeframe
  type: http
  seq: 6

http:
  method: POST
  url: http://localhost:3002/api/backtest/master/add-timeframe
  body:
    type: json
    data: |-
      {
        "timeframe": {
          "id": "5m",
          "series": {
            "candle-series": {
              "id": "candle-series-2",
              "kind": "CandleSeries",
              "level": 0,
              "params": {}
            }
          },
          "timeframe_ms": 60000
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
