info:
  name: stop-backtest
  type: http
  seq: 5

http:
  method: POST
  url: http://localhost:3002/api/backtest/master/stop-backtest
  body:
    type: json
    data: "{}"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
