info:
  name: ws-dxdy
  type: websocket
  seq: 6

websocket:
  url: wss://indexer.dydx.trade/v4/ws
  message:
    type: json
    data: |-
      {
        "type": "subscribe",

        "channel": "v4_trades",

        "id": "BTC-USD"
      }
  auth: inherit

settings:
  timeout: 0
  keepAliveInterval: 0
