info:
  name: ws-hyper
  type: websocket
  seq: 7

websocket:
  url: wss://api.hyperliquid.xyz/ws
  message:
    type: json
    data: |-
      {
        "method": "subscribe",
        "subscription": {
          "type": "trades",
          "coin": "BTC"
        }
      }
  auth: inherit

settings:
  timeout: 0
  keepAliveInterval: 0
