services:

  redis-local:
    image: redis:7
    container_name: redis_local
    restart: unless-stopped
    ports:
      - "6380:6379"
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 4gb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

  backtest-api:
    build: ./bin/api
    container_name: backtest_api
    depends_on:
      - redis-local   
    env_file:
      - ./bin/api/.env       
    ports:
      - "8100:8100"
    restart: unless-stopped

  backtest-tick:
    build: ./bin/tick
    container_name: backtest_tick
    depends_on:
      - backtest-api
    env_file:
      - ./bin/tick/.env
    restart: "no"
    volumes:
      - ./bin/tick/output:/output:ro

volumes:
  redis_data: