services:
  pulsar-local:
    image: apachepulsar/pulsar:4.2.2
    container_name: pulsar
    restart: unless-stopped
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      PULSAR_MEM: "-Xms2g -Xmx2g -XX:MaxDirectMemorySize=2g"
    volumes:
      - pulsar_data:/pulsar/data

  redis-local:
    image: redis:7
    container_name: redis_local
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --save ""
      --appendonly no
      --maxmemory 4gb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data

volumes:
  pulsar_data:
  redis_data: