services:

  backtest-api:
    build: ./bin/api                   
    container_name: backtest_api
    env_file:
      - ./bin/api/.env       
    ports:
      - "8100:8100"
    restart: unless-stopped

  backtest-tick:
    build: ./bin/tick
    container_name: backtest_tick
    depends_on:
      - backtest-api
    env_file:
      - ./bin/tick/.env
    restart: "no"
    volumes:
      - ./bin/tick/output:/app/output
